
on: [push, pull_request]
jobs:
  job_id:
    strategy:
      matrix:
        platform: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - run: g++ -o kart kart.cpp
    - run: ./kart
    - run: ./kart
